### PR TITLE
Drop wrapper and downloads patch change

### PR DESCRIPTION
**Pull request by gasinvein**
Follow-up for discussion started in #126 
- Let Telegram download files to `~/Download/Telegram Desktop` directory
- Set temp files dir to cache subdir via patch and drop warpper
  - Move this change from `telegram-cache-dir-for-downloads.patch` to `telegram-single-instance.patch`

Thanks to @ilya-fedin for the patch changes.

### CODE REVIEW

**Comment by grulja** [comment]
I can tell it doesn't work as before. If someone sends me a file (a photo for example, but as a file), I can view it with Telegram, but I can't open it with another app using "Open with". Also, if you restart Telegram, the file will be downloaded again, like it wasn't downloaded before.

**Comment by grulja** [comment]
I installed older version to compare and there it worked as expected. I could open any file sent to me using "Open with" and after starting Telegram again, that file was already downloaded.

**Comment by gasinvein** [comment]
I'm pretty sure it does work for me. Strange. Can you confirm Telegram has access to your host's `~/Download` directory?

**Comment by grulja** [comment]
It does work when I use --filesystem=home. My guess is that it doesn't work for me because $XDG_DOWNLOAD_DIR is not set in my case. This on Fedora 31 with KDE Plasma.

**Comment by ilya-fedin** [comment]
Can you show?
```
flatpak info -M org.telegram.desktop
```

**Comment by gasinvein** [comment]
`$XDG_DOWNLOAD_DIR` env var isn't set for me either. Maybe it's something wrong with your `~/.config/user-dirs.dirs`, e.g. `XDG_DOWNLOAD_DIR` there doesn't point to actual downloads folder?

**Comment by grulja** [comment]
```
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=dri;
filesystems=xdg-download;xdg-config/kdeglobals:ro;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
com.canonical.AppMenu.Registrar=talk
org.freedesktop.Notifications=talk
org.freedesktop.portal.Fcitx=talk
com.canonical.Unity=talk
```

And content of my ~/.config/user-dirs.dirs
```
XDG_DESKTOP_DIR="$HOME/"
XDG_DOWNLOAD_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/"
```

**Comment by gasinvein** [comment]
@grulja So all your `XDG_*_DIR` point to `$HOME` - it's likely to be the case.

**Comment by grulja** [comment]
I thought it comes by default from Fedora, but I might have this misconfigured for some reason. Removing that file and running xdg-user-dirs-update uses $HOME/Downloads now.

**Pull request merged**
