### PR TITLE
Don't bundle opus

### PR DESCRIPTION
**Pull request by Erick555**
It's provided in runtime. It should also fix issues after recent qt update in runtime.

### CODE REVIEW

**Comment by Erick555** [comment]
I also wonder if telegram could use [ffmpeg-full extension](https://github.com/flathub/org.gnome.Totem/blob/6894460e60e1973d682ffca145aac3b4f4406793/org.gnome.Totem.json#L62) instead of bundling own ffmpeg. I don't use telegram so someone would have to test it.

**Comment by gasinvein** [comment]
I've already tried to do something similar #106

**Comment by grulja** [comment]
Thanks, I pushed https://github.com/flathub/org.telegram.desktop/commit/32e989683add9f6d458bf051974fad47809eadc9. You were missing bump of Qt version.

**Comment by Erick555** [comment]
> How? The issue is with text rendering (assuming you are talking about #92)

By rebuilding against current qt from runtime (but I missed patch bump).

@grulja even after your patch the builds fails: https://flathub.org/builds/#/builders/39/builds/1348

Does telegram publishes pre-compiled binaries with bundled qt? If yes then maybe it's better to switch to them as building from source in those circumstances is unstable for users.

**Comment by grulja** [comment]
It failed, but hopefully fixed now. I also needed to change the location where Telegram searches for Opus includes.

Telegram does provide binaries with bundled Qt, but we are not going to use them. There are benefits of having Telegram build against Qt in the runtime, like newer version, backported fixes, smaller size of Telegram and so on.

**Comment by Erick555** [comment]
Yes but if some functionality is going to break with every qt update from runtime then I'm not sure if those benefits are worth it.

**Comment by Erick555** [comment]
> I've already tried to do something similar #106 

@gasinvein I wonder if voice issues were related to bundled opus.

**Comment by gasinvein** [comment]
@Erick555 It's not, I believe it was related to ffmpeg build options.

**Comment by Erick555** [comment]
If you know which ones then you may report it to https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by gasinvein** [comment]
@Erick555 opened https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/925. Not sure if it's FD.o SDK issue, but at least they could point to the right direction.

**Pull request closed without merging**
