### PR TITLE
Update to 2.5.4

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by gasinvein** [comment]
Please try updating tg_owt to latest commit.

**Comment by ilya-fedin** [comment]
inb4: arm fails

**Comment by ilya-fedin** [comment]
🙃

**Comment by ilya-fedin** [comment]
Add `"skip-arches": ["aarch64"]` to flathub.json

**Comment by gasinvein** [comment]
@ilya-fedin Any chance it'll be fixed upstream?

**Comment by ilya-fedin** [comment]
> Any chance it'll be fixed upstream?

arm is community maintained, so it's ulikely to be fixed until someone PR a fix

**Comment by gasinvein** [comment]
@ilya-fedin Do you know exact commit after which it broke?

**Comment by ilya-fedin** [comment]
> Do you know exact commit after which it broke?

https://github.com/desktop-app/tg_owt/commit/2c0fbe4d3d1c33d0cc9ff7c112b4db1963bea535 most likely

**Comment by gasinvein** [comment]
I think we should notify @dusxmt just in case they're willing to help again with telegram ARM builds.

**Comment by dusxmt** [comment]
I'm currently rather busy with IRL matters, so I don't know when I'll have time, but from the build message, it appears that the source file listing simply needs to be updated, some ARM Neon files aren't being built.

**Comment by gasinvein** [comment]
@dusxmt NP, thanks for the tip.
@ilya-fedin I may be mistaken but probably it's this desktop-app/tg_owt@d91d618889cc743aafd809151449012de62e5327 commit that broke ARM. It replaced arch detection from `cmake/arch.cmake` with a single OSX-only check.

**Comment by ilya-fedin** [comment]
No it fallbacks to the file: https://github.com/desktop-app/tg_owt/commit/d91d618889cc743aafd809151449012de62e5327#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR44

Even though this still looks like a hack, this is not the cause definitely.

**Comment by gasinvein** [comment]
Right. So, we should add `ooura_fft_neon.cc` to sources list?

In any case, merging it without ARM support for now. Will try to fix it in some follow-up PR.

**Comment by cho2** [comment]
Thanks!

**Pull request merged**
