### PR TITLE
Update to v2.4.14 (beta)

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Please remove the patch and changelog2appdata script

**Comment by ilya-fedin** [comment]
And looks like there unneeded empty .gitmodules

**Comment by ilya-fedin** [comment]
No, I meant both the patch and the changelog2appdata script, changelog2appdata is not a patch

**Comment by cho2** [comment]
> No, I meant both the patch and the changelog2appdata script, changelog2appdata is not a patch

@ilya-fedin Sorry, I didn't get it

**Comment by gasinvein** [comment]
@ilya-fedin Looks like upstream changelog2appdata scripts doesn't work in out-of-source builds. Fixed by changing `../changelog.txt` path to `${CMAKE_SOURCE_DIR}/changelog.txt` (see the new patch), not sure if it's correct.

**Comment by ilya-fedin** [comment]
yeah :)

**Pull request merged**
