### PR TITLE
Update to 2.4.13 beta

### PR DESCRIPTION
**Pull request by gasinvein**
Supersedes #215

### CODE REVIEW

**Comment by ilya-fedin** [comment]
That's a hack way

**Comment by gasinvein** [comment]
@ilya-fedin We can always replace the patch when someone does better. Could you suggest a proper fix?

**Comment by ilya-fedin** [comment]
We can just wait for a proper release

**Comment by gasinvein** [comment]
I think it's good to have beta version early, this way we'll know if some other (than build) issue pops up.

**Pull request merged**
