### PR TITLE
add patch to properly disable text input method on focus leave

### PR DESCRIPTION
**Pull request by camelCaseNick**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
The description of the patch sounds as it would break entering first character for search when no field is focused. I also don't understand why this should be a flathub-specific patch.

**Comment by camelCaseNick** [comment]
@ilya-fedin This is about the Wayland extensions text-input-unstable-v3, as such it changes the behaviour to on-screen keyboards and other input methods. It will not break or even change the behaviour for real keyboards. Also, this is not related to Flathub or Flatpak. As such, I plan to open an MR against desktop-app/patches.

**Comment by ilya-fedin** [comment]
> as such it changes the behaviour to on-screen keyboards and other input methods.

Yeah, that's exactly what I'm afraid of. There's a logic of focusing search field on first input and I beleive your patch will break first input, making it regular keyboard input without input method support.

**Comment by camelCaseNick** [comment]
It should open the input method on the first keystroke, then. Let me check …

**Comment by ilya-fedin** [comment]
Maybe better to create a Qt bugreport and let Qt engineers fix this?

**Comment by camelCaseNick** [comment]
Yes, I suppose, that makes sense.

**Pull request closed without merging**
