### PR TITLE
Empty commit to file PR to test build

### PR DESCRIPTION
**Pull request by wjt**
master does not build on my local machine, so I am curious if it builds on Flathub's infrastructure.

```
make[2]: Entering directory '/run/build/telegram-desktop/out/Release'
[ 54%] Updating stdafx.h
/usr/bin/cmake -E copy /run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles/stdafx.h /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h
[ 54%] Precompiling stdafx.h for Telegram (C)
[ 54%] Precompiling header stdafx.h for Telegram (C++)
/usr/lib/sdk/gcc8/bin/g++ -DNDEBUG -DNOMINMAX -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PLUGIN -DQT_WIDGETS_LIB -DQ_OS_LINUX64 -DTDESKTOP_DISABLE_AUTOUPDATE -DTDESKTOP_DISABLE_CRASH_REPORTS -DTDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME -DTDESKTOP_DISABLE_UNITY_INTEGRATION -DTGVOIP_USE_CXX11_LIB -DXXH_INLINE_ALL -D_REENTRANT -D__STDC_FORMAT_MACROS -I/run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles -I/run/build/telegram-desktop/out/Release/obj/gen -I/run/build/telegram-desktop/out/Release/../../../Libraries/opus/include -I/app/include/meta -I/app/include/range -I/app/include/range/v3 -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/minizip -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/SPMediaKeyTap -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/emoji_suggestions -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/GSL/include -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/variant/include -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/crl/src -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/xxHash -I/usr/include/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtDBus -I/usr/include/QtCore/5.9.6 -I/usr/include/QtGui/5.9.6 -I/usr/include/QtCore/5.9.6/QtCore -I/usr/include/QtGui/5.9.6/QtGui -I/run/build/telegram-desktop/out/Release/../../../Libraries/crashpad -I/run/build/telegram-desktop/out/Release/../../../Libraries/crashpad/third_party/mini_chromium/mini_chromium -I/app/include -I/app/include/opus -I/usr/lib/mkspecs/linux-g++ -I/usr/include/QtCore -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/libtgvoip  -O2 -g -Wno-deprecated-declarations -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -std=gnu++17 -O2 -g -Wno-deprecated-declarations -fstack-protector-strong -D_FORTIFY_SOURCE=2   -x c++-header -o /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h.gch/.c++ -c /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h
/usr/lib/sdk/gcc8/bin/gcc -DNDEBUG -DNOMINMAX -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PLUGIN -DQT_WIDGETS_LIB -DQ_OS_LINUX64 -DTDESKTOP_DISABLE_AUTOUPDATE -DTDESKTOP_DISABLE_CRASH_REPORTS -DTDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME -DTDESKTOP_DISABLE_UNITY_INTEGRATION -DTGVOIP_USE_CXX11_LIB -DXXH_INLINE_ALL -D_REENTRANT -D__STDC_FORMAT_MACROS -I/run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles -I/run/build/telegram-desktop/out/Release/obj/gen -I/run/build/telegram-desktop/out/Release/../../../Libraries/opus/include -I/app/include/meta -I/app/include/range -I/app/include/range/v3 -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/minizip -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/SPMediaKeyTap -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/emoji_suggestions -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/GSL/include -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/variant/include -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/crl/src -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/xxHash -I/usr/include/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtDBus -I/usr/include/QtCore/5.9.6 -I/usr/include/QtGui/5.9.6 -I/usr/include/QtCore/5.9.6/QtCore -I/usr/include/QtGui/5.9.6/QtGui -I/run/build/telegram-desktop/out/Release/../../../Libraries/crashpad -I/run/build/telegram-desktop/out/Release/../../../Libraries/crashpad/third_party/mini_chromium/mini_chromium -I/app/include -I/app/include/opus -I/usr/lib/mkspecs/linux-g++ -I/usr/include/QtCore -I/run/build/telegram-desktop/out/Release/../../Telegram/ThirdParty/libtgvoip  -O2 -g -Wno-deprecated-declarations -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC   -x c-header -o /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h.gch/.c -c /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h
In file included from /run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles/data/data_types.h:11,
                 from /run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles/data/data_file_origin.h:11,
                 from /run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles/ui/images.h:11,
                 from /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h:91:
/run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles/ui/text/text.h:10:10: fatal error: private/qfontengine_p.h: No such file or directory
 #include "private/qfontengine_p.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Telegram.dir/build.make:79: Telegram_pch/stdafx.h.gch/.c++] Error 1
make[2]: Leaving directory '/run/build/telegram-desktop/out/Release'
make[1]: *** [CMakeFiles/Makefile2:91: CMakeFiles/Telegram.dir/all] Error 2
make[1]: Leaving directory '/run/build/telegram-desktop/out/Release'
make: *** [Makefile:87: all] Error 2
Error: module telegram-desktop: Child process exited with code 2
```

### CODE REVIEW

**Comment by wjt** [comment]
bot, build

**Comment by wjt** [comment]
I guess I can't bot, build this because I am not a privileged person.

**Comment by jurf** [comment]
bot, build

**Comment by wjt** [comment]
Interesting, the file exists at `/usr/include/QtGui/5.9.7/QtGui/private/qfontengine_p.h` but the include path has `5.9.6`. I guess this comes from the hardcoded version number in `Avoid-depending-on-static-libraries.patch`…

**Comment by wjt** [comment]
Will fix on #46.

**Pull request closed without merging**
