### PR TITLE
Force xcb plugin for better compatibility

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by YaLTeR** [comment]
Is there a way to disable this? I've been running Telegram on Wayland because:
1. When running through Xwayland it ignores the "show tray icon" setting and always shows it (on [Waybar](https://github.com/Alexays/Waybar)).
1. When running through Xwayland it hits [this sway clipboard issue](https://github.com/swaywm/sway/issues/4007) which is extremely annoying.

**Comment by grulja** [comment]
> Is there a way to disable this? I've been running Telegram on Wayland because:
> 
> 1. When running through Xwayland it ignores the "show tray icon" setting and always shows it (on [Waybar](https://github.com/Alexays/Waybar)).
> 2. When running through Xwayland it hits [this sway clipboard issue](https://github.com/swaywm/sway/issues/4007) which is extremely annoying.

You can change this with --env=QT_QPA_PLATFORM=wayland. 

Like running Telegram with: **flatpak run --env=QT_QPA_PLATFORM=wayland org.telegram.desktop**

**Comment by YaLTeR** [comment]
Thanks, that worked.

**Comment by gasinvein** [comment]
@grulja Do you think disabling Wayland for everyone to only fix decorations for Gnome users worth it? Maybe it would be better to do the opposite - enable Wayland by default and add a note somewhere for Gnome users?

**Comment by grulja** [comment]
> @grulja Do you think disabling Wayland for everyone to only fix decorations for Gnome users worth it? Maybe it would be better to do the opposite - enable Wayland by default and add a note somewhere for Gnome users?

It's not about decorations, people reported some glitches and same glitches were reported sometime ago when I disabled Wayland before. See https://quietlife.nl/telegram-flatpak-glitch.webm for example.

**Pull request merged**
