### PR TITLE
Update to 1.9.4

### PR DESCRIPTION
**Pull request by gasinvein**
Most patches we used to apply are merged upstream now.

### CODE REVIEW

**Comment by gasinvein** [comment]
bot, build

**Comment by ilya-fedin** [comment]
https://github.com/flathub/org.telegram.desktop/blob/fbdb6d9e31f2b606fc9032aa0dfe45c9bde95144/org.telegram.desktop.json#L206
Why not just use GenericCacheLocation in telegram-cache-dir-for-downloads.patch?

**Comment by gasinvein** [comment]
I wonder why the download path is pointed to cache directory in the first path of the patch? Telegram has access to `xdg-download` anyway and could just save files there.

**Comment by grulja** [comment]
> I wonder why the download path is pointed to cache directory in the first part of the patch? Telegram has access to `xdg-download` anyway and could just save files there.

I think I did this because if someone sends you a picture and you try to open it (instead of download it), it will save it to /tmp and you won't be to able to open it from there. Anyway, all this is really needed to make this all work properly.

**Comment by gasinvein** [comment]
@grulja I'm talking about this portion
https://github.com/flathub/org.telegram.desktop/blob/1dff50e56a9eda62e9c5cf8480bf7a5e0782b81a/patch/telegram-cache-dir-for-downloads.patch#L3-L13
Why `QStandardPaths::DownloadLocation` isn't fine?

**Comment by grulja** [comment]
Because the download location inside the sandbox won't be accessible outside. You need it accessible outside to be able to open a downloaded file with other apps. That's why the TMPDIR is set to a different location.

**Comment by gasinvein** [comment]
>the download location inside the sandbox won't be accessible outside

Why? Telegram has access to download dir.
https://github.com/flathub/org.telegram.desktop/blob/1dff50e56a9eda62e9c5cf8480bf7a5e0782b81a/org.telegram.desktop.json#L20

**Comment by ilya-fedin** [comment]
> That's why the TMPDIR is set to a different location.

You can use QStandardPaths::GenericCacheLocation thay uses $XDG_CACHE_HOME

**Comment by grulja** [comment]
Feel free to change it and verify if it works. Verify if opening a file directly works and if downloading works. I don't use Telegram at the moment and I  won't be able to test this during weekend.

**Comment by gasinvein** [comment]
@grulja Just tested - without the [first part](https://github.com/flathub/org.telegram.desktop/pull/126#issuecomment-575883957) of the patch, Telegram downloads files to `~/Downloads/Telegram Desktop` as expected. Opening and opening containing directory works, too.
One note - looks like the default setting for download location persist and doesn't change from "cache" to "downloads" automatically after rebuilt Telegram is launched. Had to change the setting to some custom path and then change it back to default.

**Pull request merged**
