### PR TITLE
[WIP] Update to 1.9.3

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by grulja** [comment]
bot, build

**Comment by gasinvein** [comment]
@grulja Maybe backport this changes telegramdesktop/tdesktop#6956? Telegram now can be build with pure cmake (no gyp), and almost all patches can be dropped.

**Comment by gasinvein** [comment]
I've already managed to build telegram with the "packaged" patches, see [this branch](https://github.com/gasinvein/org.telegram.desktop/tree/update/1.9.3/packaged). Can open a PR with it if you'd like.

**Comment by grulja** [comment]
Awesome!! Please open a PR. Thank you.

**Pull request closed without merging**
