### PR TITLE
Update 1.9.3 patches

### PR DESCRIPTION
**Pull request by gasinvein**
- Update patches from packaged build pull requests
- Redo 6945 on top of 6956
- Backport telegramdesktop/tdesktop@100fed362271ada828fdaeb27e52f660a5a05d18 (needed to apply other patches)
- Building bundled libtgvoip and rlottie now possible when doing "packaged", do so

### CODE REVIEW

**Comment by grulja** [comment]
You don't need to include upstream patches, you can point to a specific commit instead of git tag.

**Comment by gasinvein** [comment]
This would mean we'll build master branch instead of latest release, since PRs are opened against master.

**Comment by gasinvein** [comment]
Also there are multiple git repos since many Telegram parts were split into submodules. Not sure how to handle this.

**Comment by grulja** [comment]
Ok then.

**Pull request merged**
