### PR TITLE
Update tg_owt for more ARM optimizations

### PR DESCRIPTION
**Pull request by ilya-fedin**
Checking build with some optimizations enabled (not sure how else it is possible to do locally without owning an ARM host)...

### CODE REVIEW

**Comment by ilya-fedin** [comment]
bot, build

**Comment by gasinvein** [comment]
If you're going to merge it before your changes get upstream, please add them as patches on top of the original source instead of using your fork directly.

**Comment by ilya-fedin** [comment]
> If you're going to merge it before your changes get upstream

No, I'm just testing changes on Flathub CI

**Comment by ilya-fedin** [comment]
But the build is successful, so it's worth to update tg_owt

**Pull request merged**
