### PR TITLE
Update to 1.9.7

### PR DESCRIPTION
**Pull request by gasinvein**
- Install via cmake now supported, use it and drop `post-install` commands
- Single instance in flatpak is now specifically supported, so related patch isn't needed

### CODE REVIEW

**Comment by grulja** [comment]
Do you think it's time to push this also to stable? Do you plan in future to keep contributing to Telegram here on Flathub? If so, we can ask admins to give you permissions so you can merge your PRs yourself.

**Comment by gasinvein** [comment]
> Do you think it's time to push this also to stable?

I believe so. Didn't notice any problems since 1.9.4.
> Do you plan in future to keep contributing to Telegram here on Flathub?

Telegram drastically decreased downstream maintenance complexity since last PRs. Hopefully now it would require only bumping version.

**Comment by grulja** [comment]
> > Do you think it's time to push this also to stable?
> 
> I believe so. Didn't notice any problems since 1.9.4.

Ok, I will merge it to master.

> > Do you plan in future to keep contributing to Telegram here on Flathub?
> 
> Telegram drastically decreased downstream maintenance complexity since last PRs. Hopefully now it would require only bumping version.

Yeah, it's now not complex at all and thank you for that. It was a pain before and almost every Telegram update broke it so I had to rebase patches etc.

**Comment by gasinvein** [comment]
> Yeah, it's now not complex at all and thank you for that.

We should thank @ilya-fedin and @xvitaly for that. I've just pulled the patches.

**Pull request merged**
