### PR TITLE
Update to v2.4.13 (beta)

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by gasinvein** [comment]
There is 2.4.13 beta already. Try updating to it.

**Comment by ilya-fedin** [comment]
Most likely it won't build either

**Comment by ilya-fedin** [comment]
Looks like tg_owt should be updated

**Comment by ilya-fedin** [comment]
Add `-DBUILD_SHARED_LIBS=OFF` to tg_owt cmake arguments

**Comment by ilya-fedin** [comment]
inb4: link error

**Comment by ilya-fedin** [comment]
Where's my prize? :)

Jokes aside, preston doesn't adapt build for anything other than official binaries and we should wait until community fixes the cmake scripts

**Comment by gasinvein** [comment]
Looks like it should link with shared `xcb-keysyms` or whatever exports the needed symbols?

**Comment by ilya-fedin** [comment]
not only xcb-keysyms, there's a couple of new xcb dependencies due to the new platform code

**Comment by ilya-fedin** [comment]
Why don't you amend the first commit?

**Comment by gasinvein** [comment]
@cho2 I guess I'll try to fix linking myself. Thanks for your participation anyway.

**Pull request closed without merging**
