### PR TITLE
update flatpak runtime to 22.08

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
I don't believe we can do this as 22.08 has openssl 3.0 that is not supported by tdesktop.

**Comment by Etaash-mathamsetty** [comment]
none of those issues are related with this PR, or are they?

**Comment by Etaash-mathamsetty** [comment]
> I don't believe we can do this as 22.08 has openssl 3.0 that is not supported by webrtc version used by tdesktop.

oh mb then

**Comment by ilya-fedin** [comment]
> oh mb then, but is it not possible to get it to support openssl 3.0?

If you volunteer for that then no problem. It's not planned by main tdesktop developers though, so may take years otherwise.

**Comment by Etaash-mathamsetty** [comment]
> > oh mb then, but is it not possible to get it to support openssl 3.0?
> 
> If you volunteer for that then no problem. It's not planned by main tdesktop developers though, so may take years otherwise.

seems like quite a lot of it is written for openssl 1.x, and I don't think I have that much time on my hands to port it over, so I guess I this PR will have to wait

**Pull request closed without merging**
