### PR TITLE
Enable ARM and aarch64

### PR DESCRIPTION
**Pull request by nedrichards**
NOTE: DO NOT MERGE THIS PR YET.

This is to work on re-enabling ARM and aarch64 for telegram, using the flathub builders.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by barthalion** [comment]
Has the upstream changed the code that required some architecture-specific defines? I admit I was lazy about pursuing this further by disabling arm altogether but it won't work as is.

**Comment by jurf** [comment]
bot, build

**Comment by alexlarsson** [comment]
bot, build

**Comment by alexlarsson** [comment]
bot, build

**Pull request merged**
